Update homework.md
CodeYourFuture/GitHomeworkFixErrors pull request #118
Opened 2021-05-10 12:38 UTC by Haliema26

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

2021-05-10 13:42 UTC, konikalily requested changes
Hi Haliema, I think the primary objective of "forking" is copying a repository, so that we dont change the original one. Good job anyway with other questions. :-)

2021-05-10 13:44 UTC, konikalily reviewed
Nice Work

2021-05-10 13:56 UTC, konikalily requested changes
I suggested some change. Thank you

2021-05-10 13:56 UTC, konikalily commented on homework.md
> +You can make changes to it without effecting the original project.
You copy the repository by "forking" in github.

2021-05-11 10:40 UTC, xtremelibasic commented on homework.md
> +  text-transform: uppercase;
Hi Haliema, in question 6 you did not need to add the "text-transform:uppercase" line because we were asked to just select every h1 tag.

2021-05-11 10:40 UTC, xtremelibasic commented on homework.md
> +A programming language used on the webpages.
Here, I it would be easier to understand by  saying JavaScript is used to make webpages dynamic.

2021-05-11 15:39 UTC, Haliema26 commented
> I hope my comments are helpfull.

 Yes You add valuable points Amanda🙂

2021-05-27 17:09 UTC, SteveLeicester reviewed
Thanks Haliema - nice work,  Agree with the comment on JavaScript and web pages. Dynamic and also interactive.  Allowing many more things to happen depending on what the user did.

2021-12-13 19:34 UTC, closed without merging