LinusHomeworkFixed.md
CodeYourFuture/GitHomeworkFixErrors pull request #17
Opened 2020-11-02 16:03 UTC by Bahia369

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

2020-11-02 17:21 UTC, mikinet requested changes
Hi Bahia, I think this answer about JS in Q.9 is just fine, but you can make it even much better if you mention something special about JS. Cheers.

2020-11-02 20:06 UTC, jip1984 commented on homework.md
> +Hyper Text Markup Language
Hypertext is one word (Just commenting for homework purposes)

2020-11-02 20:07 UTC, jip1984 commented on homework.md
> +When you send a file over the internet and is allowed t obe viewed and edited by another person
You make local code changes and then submit those changes to a remote project maintainer for review before those changes are implemented, or merged. This is called a pull request; you are requesting that someone reviews and approves your changes before they become final.

2020-11-20 00:35 UTC, samia-pk commented on homework.md
>  What is the Git History log?
Git History log: it shows you all the history of changes in a file.

please leave feedback on my work also. thanks

2020-11-20 00:42 UTC, samia-pk commented on homework.md
>  What is JavaScript?
JavaScript: it helips you to make your web page more interactive in various way.

please leave feedback on my work also. thanks

2020-11-20 00:42 UTC, samia-pk commented on homework.md
>  ## Question 12
Git History log: it shows you all the history of changes in a file.

please leave feedback on my work also. thanks

2021-12-13 19:32 UTC, closed without merging