South Africa -- Ntshembo Hlongwane
CodeYourFuture/GitHomeworkFixErrors pull request #33
Opened 2020-11-21 19:13 UTC by Ntshembo-Hlongwane1

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

2020-11-22 04:31 UTC, RynoFourieZA commented
Good Day Ntshembo, hope everything is good and well. I want to point out on questions 4 and 12 you have a typo error.

2020-11-22 15:03 UTC, Ntshembo-Hlongwane1 commented
Hey Ryno great catch! However I do not see a typo in question 12 could you at least highlight specifically where you see that.

Q12  --> What is the Git History log?
>  This is the entire log/list of all your commits that you have made in that repo/branch if the is more than one branch

2020-11-22 16:33 UTC, RynoFourieZA commented
>``` -This is the entire log/list of all your commits that you have made in that repo/branch if the is more than one branch
+ - This is the entire log/list of all your commits that you have made in that repo/branch if there is more than one branch
```

2020-11-24 14:29 UTC, RynoFourieZA commented
Good day, Ntshembo sorry for the late reply, as I'm reading through question 12 there seems to be no typo error I thought you needed to replace the second _the_ with _there_.

2020-11-25 13:07 UTC, Samuelkau commented on homework.md
> +- 4
Your answer looks correct

2020-11-25 13:13 UTC, Samuelkau requested changes

2020-11-25 13:13 UTC, Samuelkau commented on homework.md
> +- White
Light

2020-11-25 21:20 UTC, KudahShambare commented
Hello bro, consider filling your details on the first comment.

2020-11-26 08:49 UTC, Ntshembo-Hlongwane1 commented
@KudahShambare What details please highlight that I'm lost

2020-11-26 09:10 UTC, KudahShambare commented
Your Name:
Your City:
Your Slack Name:
........This template, I think that you are supposed to fill it up.

2020-11-26 09:55 UTC, Ntshembo-Hlongwane1 commented
Oh that I thought that was not necessary but okay let me do it

2021-12-13 19:32 UTC, closed without merging