South Africa - Chandre De Wet - Github - 1
CodeYourFuture/GitHomeworkFixErrors pull request #41
Opened 2020-11-23 20:57 UTC by chandredewet

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

2020-11-24 18:34 UTC, DouglasVDM commented
Hi Chandre, You are making good progress. No judgment for not completing the homework. You are very busy setting up our coursework.

2020-11-25 16:30 UTC, Samuelkau requested changes

2020-11-25 16:30 UTC, Samuelkau commented on homework.md
> +Light
Opposite of black could be light, or maybe white?

2020-11-25 16:30 UTC, Samuelkau commented on homework.md
> +Don't have a calculator
(",) I will help you here answer is 12240

2020-11-25 16:30 UTC, Samuelkau commented on homework.md
> +(Too tired to complete this)
I will have to bring you an energy drink lol. The answer for this is Hypertext Markup Language

2020-11-25 16:30 UTC, Samuelkau commented on homework.md
> +(Too tired to complete this)
Try and complete the other questions and I will assist/review them further - happy research (",)

2021-12-13 19:33 UTC, closed without merging