Westmidlands Class 2 - Senait Ekubai -Github & Github Desktop- WEEK_1
CodeYourFuture/GitHomeworkFixErrors pull request #7
Opened 2020-11-01 13:23 UTC by SenaitEkubai

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

2020-11-01 15:20 UTC, Know-Thyself approved these changes
I believe that you have done a pretty good job.
Well done Senait!

2020-11-01 15:22 UTC, mikinet commented
Good product you've got there. I figure you must have forgotten to fill the details in the file by accident. You can make your assignment complete by doing so.

2020-11-01 15:29 UTC, mikinet requested changes
I see most of your answers are better than mine, Senait. It'll be perfect if you go through it once more and eliminate the few discrepancies. Cheers.
Also, feel free to review mine, if you've got the time. I'd appreciate it. Thanks!

2020-11-02 00:03 UTC, ironkamosi commented on homework.md
> +Cascading Style Sheets
Hi Senait,

Your answer explains what CSS stands for. Can you briefly explain how and why it is used ?

All the best,

Aaron

2021-12-13 19:32 UTC, closed without merging