London Class 7  - Sharon Akaka - GIT/GITHUB - Week 1
CodeYourFuture/GitHomeworkFixErrors pull request #88
Opened 2020-12-03 22:04 UTC by Sharon-Akaka

# Your Details

- Your Name: Sharon Akaka
- Your City: London
- Your Slack Name: Sharon Akaka

# Homework Details

- Module: Git/Github
- Week: 1

2020-12-03 23:02 UTC, Domenico-cyf requested changes

2020-12-03 23:02 UTC, Domenico-cyf commented on homework.md
> +What three problems does Git & Github solve?
Well done on spotting spelling mistake. I didn't

2020-12-05 11:14 UTC, ASLANDENIZ reviewed
I finish my review, well done.

2020-12-05 11:14 UTC, ASLANDENIZ commented on homework.md
> +What is the 2 _ 3 _ 6 _ 1 _ 10 \* 34?
The question also changed with your latest update I guess, the original question was different. (multiplication signs).

2021-07-21 15:37 UTC, closed without merging