London Class 7 - Domenico Delli Carri - GitHub - Homeworks
CodeYourFuture/GitHomeworkFixErrors pull request #93
Opened 2020-12-04 18:40 UTC by Domenico-cyf

London Class 7 - Domenico DC - GitHub - Homeworks

# Your Details

- Your Name: Domenico DC
- Your City: London
- Your Slack Name: Domenico DC

# Homework Details

- Module: GitHub
- Week: Homework

2020-12-04 22:03 UTC, Laura-TM commented
Hi Domenico, well done on knowing how to edit your own work through the website! Perhaps you want to look at a small typo on Q5?

2020-12-04 22:03 UTC, Laura-TM commented
Just left a comment on your submission.

2020-12-05 13:32 UTC, akbasmustafa requested changes

2020-12-05 22:35 UTC, AhmadJanah commented
Hi Domenico, It is a great job, well done.

Your answer to question 11 is great but if you add that it will open a pull request.

Thanks.

2021-12-13 19:34 UTC, closed without merging